id = "webvtt"
name = "WebVTT"
version = "1.0.0"
schema_version = 1
authors = ["Marcus Linder <mlinder@gmail.com>"]
description = "WebVTT subtitles and captions"
repository = "https://github.com/mlinder/zed-webvtt"

languages = ["languages/webvtt"]
snippets = ["snippets/webvtt.json"]

[grammars.webvtt]
repository = "https://github.com/mlinder/tree-sitter-webvtt"
rev = "2afbfa72898392dbbc9d50bc008aea2b8ff778ee"
